[package]
name = "walle-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
robotics_lib = { path = "./lib/Robotic-Lib" }
oxagworldgenerator = { path = "./lib/oxagworldgenerator" }
rand = "0.8.5"
time = "0.3.36"
strum = "0.26.2"
bevy = { version = "0.13.2", features = ["default", "dynamic_linking"] }
bincode = "1.3.3"
lazy_static = "1.4.0"

[[bin]]
name = "walle-visualizer"
path = "src/main.rs"
