[package]
name = "walle-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
robotics_lib = { version = "0.1.21", path = "lib/robotics_lib-0.1.21" }
tokio = { version = "1.37.0", features = ["time", "rt", "rt-multi-thread", "macros"] }
roomba_robot_test = { git = "ssh://git@github.com/RustyPripyat/roomba_robot_test.git" }
common-messages = { git = "ssh://git@github.com/RustyPripyat/common-messages.git" }
