[package]
name = "walle-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
robotics_lib = { path = "../Robotic-Lib" }
exclusion_zone_world_generator = { path = "../World-Generator" }
message-io = { version = "0.18" }
bincode = "1.3.3"
serde = { version = "1.0.197", features = ["derive"] }

[lib]
path = "src/lib.rs"

[workspace]
members = ["src/bins/client", "src/bins/server"]

